2019-01-14 10:11:54 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: ARGUS)
2019-01-14 10:11:54 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-7-6.1.7601-SP1
2019-01-14 10:11:54 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'ARGUS', 'COMPRESSION_ENABLED': False, 'CONCURRENT_ITEMS': 200, 'CONCURRENT_REQUESTS': 100, 'COOKIES_ENABLED': False, 'DOWNLOAD_MAXSIZE': 10000000, 'DOWNLOAD_TIMEOUT': 20, 'FEED_URI': 'file:///C:/ARGUS-webarchive/ARGUS-webarchive/items/ARGUS/textspider/6e061e6217dc11e9bbbc00505680340c.jl', 'LOG_FILE': 'logs\\ARGUS\\textspider\\6e061e6217dc11e9bbbc00505680340c.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'ARGUS.spiders', 'REACTOR_THREADPOOL_MAXSIZE': 30, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['ARGUS.spiders']}
2019-01-14 10:11:54 [py.warnings] WARNING: c:\python36\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.feedexport.FeedExporter` class is deprecated, use `scrapy.extensions.feedexport.FeedExporter` instead
  ScrapyDeprecationWarning)

2019-01-14 10:11:54 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-01-14 10:11:54 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-01-14 10:11:54 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-01-14 10:11:54 [scrapy.middleware] INFO: Enabled item pipelines:
['ARGUS.pipelines.TextPipeline']
2019-01-14 10:11:54 [scrapy.core.engine] INFO: Spider opened
2019-01-14 10:11:54 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20010926120604/http://www.agcity.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/19991004023619/http://www.aamex.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20010926120604/http://www.agcity.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20111130230021/http://www.adler-wohndesign.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20010402042903/http://www.alfred-eichelberger.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20041121093029/http://www.alre.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20091024033122/http://www.1892.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20020526005831/http://www.allbau-berlin.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20081208063304/http://www.adr-berlin.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20020916224703/http://www.aks-berlin.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20020205200435/http://www.ambeg.de:80/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/20091024033122/http://www.1892.de:80/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20010204125100/http://www.abe-minuth.de:80/index2.htm> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20001206213200/http://www.ambrosetti.de:80/start.htm> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20070520082256/http://www.3s-gmbh.de:80/main.htm> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET http://web.archive.org/> (referer: None)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20111231121453/http://www.adler-wohndesign.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20011130111943/http://www.agcity.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/> (referer: http://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20020524153117/http://www.ambeg.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20081208063304/http://joomla.org/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20110209045017/http://www.alre.de/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20011130111943/http://www.agcity.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/19991127231323/http://aamex.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20020806101022/http://allbau-berlin.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20010515222555/http://www.alfred-eichelberger.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20021128171523/http://aks-berlin.de:80/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20090321075628/http://www.adr-berlin.de:80/> (referer: https://web.archive.org/web/20081208063304/http://joomla.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20070825105518/http://www.3s-gmbh.de:80/main.htm> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20021210043512/http://www.ambrosetti.de:80/start.htm> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:11:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20090321075628/http://joomla.org/> (referer: https://web.archive.org/web/20090321075628/http://www.adr-berlin.de:80/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:12:00 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20060309092124/http:/www.abe-minuth.de/main.htm> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:12:00 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20060309092124/http:/www.abe-minuth.de/main.htm> (referer: https://web.archive.org/web/20060309092124/http:/www.abe-minuth.de/main.htm)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 278, in processURLstack
    yield scrapy.Request(urlstack.pop(0).to_archive_url(), meta={"loader": loader, "urlstack": urlstack, "fingerprints": fingerprints, 'handle_httpstatus_all': True}, dont_filter=True, callback=self.parse_archive_subpage, errback=self.processURLstack)
AttributeError: 'str' object has no attribute 'to_archive_url'
2019-01-14 10:12:01 [scrapy.core.engine] INFO: Closing spider (finished)
2019-01-14 10:12:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 33744,
 'downloader/request_count': 108,
 'downloader/request_method_count/GET': 108,
 'downloader/response_bytes': 2138240,
 'downloader/response_count': 108,
 'downloader/response_status_count/200': 71,
 'downloader/response_status_count/302': 36,
 'downloader/response_status_count/403': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 1, 14, 9, 12, 1, 224896),
 'item_scraped_count': 15,
 'log_count/ERROR': 70,
 'log_count/INFO': 7,
 'log_count/WARNING': 1,
 'request_depth_max': 7,
 'response_received_count': 85,
 'scheduler/dequeued': 108,
 'scheduler/dequeued/memory': 108,
 'scheduler/enqueued': 108,
 'scheduler/enqueued/memory': 108,
 'spider_exceptions/AttributeError': 70,
 'start_time': datetime.datetime(2019, 1, 14, 9, 11, 54, 839257)}
2019-01-14 10:12:01 [scrapy.core.engine] INFO: Spider closed (finished)
