2019-01-14 10:01:31 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: ARGUS)
2019-01-14 10:01:31 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-7-6.1.7601-SP1
2019-01-14 10:01:31 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'ARGUS', 'COMPRESSION_ENABLED': False, 'CONCURRENT_ITEMS': 200, 'CONCURRENT_REQUESTS': 100, 'COOKIES_ENABLED': False, 'DOWNLOAD_MAXSIZE': 10000000, 'DOWNLOAD_TIMEOUT': 20, 'FEED_URI': 'file:///C:/ARGUS-webarchive/ARGUS-webarchive/items/ARGUS/textspider/fa97b4e817da11e990da00505680340c.jl', 'LOG_FILE': 'logs\\ARGUS\\textspider\\fa97b4e817da11e990da00505680340c.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'ARGUS.spiders', 'REACTOR_THREADPOOL_MAXSIZE': 30, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['ARGUS.spiders']}
2019-01-14 10:01:31 [py.warnings] WARNING: c:\python36\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.feedexport.FeedExporter` class is deprecated, use `scrapy.extensions.feedexport.FeedExporter` instead
  ScrapyDeprecationWarning)

2019-01-14 10:01:31 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-01-14 10:01:31 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-01-14 10:01:31 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-01-14 10:01:31 [scrapy.middleware] INFO: Enabled item pipelines:
['ARGUS.pipelines.TextPipeline']
2019-01-14 10:01:31 [scrapy.core.engine] INFO: Spider opened
2019-01-14 10:01:31 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-01-14 10:01:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20161213020345/http://www.aamex.de/home/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/20161203034520/http://alre.de/de/home-company/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20161126144357/http://www.allbau-gruppe.de/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/20161003025205/http://www.ambeg.de/de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160307232331/http://aks-berlin.de/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20161002020610/http://alpha-gmbh.de/> (referer: https://web.archive.org/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160428101315/http://www.alfred-eichelberger.de/> (referer: https://web.archive.org/web/20161005032308/http://alfred-eichelberger.de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20161016151609*/https://www.agcity.de/> (referer: https://web.archive.org/web/20160819022814/http://www.agcity.de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20170213164358*/https://www.1892.de/> (referer: https://web.archive.org/web/20170213164358/http://www.wbgd.de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20161016151609*/https://www.agcity.de/> (referer: https://web.archive.org/web/20160819022814/http://www.agcity.de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160326185242/http://www.abe-minuth.de/> (referer: https://web.archive.org/web/20180321012518/http://abe-minuth.de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20161108012655/http://www.adr-berlin.de/> (referer: https://web.archive.org/web/20180307071741/http://adr-berlin.de/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:45 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/> (referer: https://web.archive.org/web/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\textspider.py", line 279, in processURLstack
    yield scrapy.Request(url, callback=self.parse, meta={"ID": ID}, dont_filter=True, errback=self.errorback)
NameError: name 'url' is not defined
2019-01-14 10:01:45 [scrapy.core.engine] INFO: Closing spider (finished)
2019-01-14 10:01:45 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 28682,
 'downloader/request_count': 90,
 'downloader/request_method_count/GET': 90,
 'downloader/response_bytes': 1782662,
 'downloader/response_count': 90,
 'downloader/response_status_count/200': 41,
 'downloader/response_status_count/302': 49,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 1, 14, 9, 1, 45, 568336),
 'log_count/ERROR': 15,
 'log_count/INFO': 7,
 'log_count/WARNING': 1,
 'request_depth_max': 7,
 'response_received_count': 72,
 'scheduler/dequeued': 90,
 'scheduler/dequeued/memory': 90,
 'scheduler/enqueued': 90,
 'scheduler/enqueued/memory': 90,
 'spider_exceptions/NameError': 15,
 'start_time': datetime.datetime(2019, 1, 14, 9, 1, 31, 539934)}
2019-01-14 10:01:45 [scrapy.core.engine] INFO: Spider closed (finished)
