2019-03-04 08:43:59 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: ARGUS)
2019-03-04 08:43:59 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-7-6.1.7601-SP1
2019-03-04 08:43:59 [scrapy.crawler] INFO: Overridden settings: {'AJAXCRAWL_ENABLED': True, 'BOT_NAME': 'ARGUS', 'COMPRESSION_ENABLED': False, 'CONCURRENT_ITEMS': 200, 'CONCURRENT_REQUESTS': 100, 'COOKIES_ENABLED': False, 'DOWNLOAD_MAXSIZE': 10000000, 'DOWNLOAD_TIMEOUT': 20, 'FEED_URI': 'file:///C:/ARGUS-webarchive/ARGUS-webarchive/items/ARGUS/webarchive/43925bdc3e5111e989dc00505680340c.jl', 'LOG_FILE': 'logs\\ARGUS\\webarchive\\43925bdc3e5111e989dc00505680340c.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'ARGUS.spiders', 'REACTOR_THREADPOOL_MAXSIZE': 30, 'REDIRECT_MAX_TIMES': 2, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['ARGUS.spiders']}
2019-03-04 08:43:59 [py.warnings] WARNING: c:\python36\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.feedexport.FeedExporter` class is deprecated, use `scrapy.extensions.feedexport.FeedExporter` instead
  ScrapyDeprecationWarning)

2019-03-04 08:43:59 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-03-04 08:43:59 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-03-04 08:43:59 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-03-04 08:43:59 [scrapy.middleware] INFO: Enabled item pipelines:
['ARGUS.pipelines.TextPipeline']
2019-03-04 08:43:59 [scrapy.core.engine] INFO: Spider opened
2019-03-04 08:43:59 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-03-04 08:44:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20130223235937id_/http://www.zew.de/en/presse/> (referer: https://www.zew.de/en/presse/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:44:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160322115233id_/http://www.zew.de/en/presse/> (referer: https://www.zew.de/en/presse/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:44:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20181012144529id_/https://www.zew.de/en/presse/> (referer: https://www.zew.de/en/presse/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:44:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160130071316id_/http://www.zew.de/en/kontakt/> (referer: https://www.zew.de/en/kontakt/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:01 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160130071316id_/http://www.zew.de/en/kontakt/> (referer: https://www.zew.de/en/kontakt/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:01 [scrapy.extensions.logstats] INFO: Crawled 41 pages (at 41 pages/min), scraped 0 items (at 0 items/min)
2019-03-04 08:45:01 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160331230739id_/http://www.zew.de/en/team/> (referer: https://www.zew.de/en/team/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:02 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20181126082226id_/https://www.zew.de/en/team/> (referer: https://www.zew.de/en/team/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:02 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160331050829id_/http://www.zew.de/en/kontakt/> (referer: https://www.zew.de/en/kontakt/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:06 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20181019092200id_/https://www.zew.de/en/kontakt/> (referer: https://www.zew.de/en/kontakt/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20110417160745id_/http://www.zew.de/en/presse> (referer: https://www.zew.de/en/presse/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:16 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20190303223006id_/https://www.focus.de/sport/> (referer: https://www.focus.de/sport/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160324054253id_/http://www.focus.de/wissen/> (referer: https://www.focus.de/wissen/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20110422223203id_/http://www.focus.de/kultur/> (referer: https://www.focus.de/kultur/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:19 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20190303222919id_/https://www.focus.de/wissen/> (referer: https://www.focus.de/wissen/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:19 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20130407045519id_/http://www.focus.de/kultur/> (referer: https://www.focus.de/kultur/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20190303222941id_/https://www.focus.de/kultur/> (referer: https://www.focus.de/kultur/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://web.archive.org/web/20160324054325id_/http://www.focus.de/kultur/> (referer: https://www.focus.de/kultur/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python36\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:30 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.focus.de/kultur/> (referer: https://web.archive.org/web/20100913021523id_/http://www.focus.de/wissen/)
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "C:\ARGUS-webarchive\ARGUS-webarchive\ARGUS\spiders\webarchive.py", line 316, in processURLstack
    elif len(urlstack) == 0 and len(current_datestack) == 0:
NameError: name 'current_datestack' is not defined
2019-03-04 08:45:30 [scrapy.core.engine] INFO: Closing spider (finished)
2019-03-04 08:45:30 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 5,
 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 5,
 'downloader/request_bytes': 22391,
 'downloader/request_count': 68,
 'downloader/request_method_count/GET': 68,
 'downloader/response_bytes': 11281356,
 'downloader/response_count': 63,
 'downloader/response_status_count/200': 57,
 'downloader/response_status_count/301': 5,
 'downloader/response_status_count/403': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 3, 4, 7, 45, 30, 567383),
 'log_count/ERROR': 18,
 'log_count/INFO': 8,
 'log_count/WARNING': 1,
 'request_depth_max': 7,
 'response_received_count': 60,
 'scheduler/dequeued': 68,
 'scheduler/dequeued/memory': 68,
 'scheduler/enqueued': 68,
 'scheduler/enqueued/memory': 68,
 'spider_exceptions/NameError': 18,
 'start_time': datetime.datetime(2019, 3, 4, 7, 43, 59, 599287)}
2019-03-04 08:45:30 [scrapy.core.engine] INFO: Spider closed (finished)
